[tasks.fmt]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["test"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean", "test"]

[tasks.all]
dependencies = [
    "run"
]